version: '3.8'

services:
  app:
    image: us-west1-docker.pkg.dev/your-gcp-project-id/tracker-repo/tracker-app:latest
    init: true
    container_name: tracker-app
    restart: always
    volumes:
      - ./data:/app/data
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_PATH=data/placement.db
    networks:
      - web_net

networks:
  web_net:
    external: true

